### PR TITLE
Create translations_hu.json

### PR DESCRIPTION
**Pull request by mpeter1975**
Hungarian translation

### CODE REVIEW

**Comment by newloran2** [comment]
Hello mpeter1975,

Thank's for your contribution.
I made a new Hungarian translation resource on transifex https://www.transifex.com/projects/p/emplexer/
if possible please follow the translation there, it's easier to follow what was translated or not besides whole new string I add those responsible are notified.

**Comment by astrago** [comment]
Hello newloran2,

I sent mail(new hungarian translation)

**Comment by newloran2** [comment]
Hello astrago,

Thank's for your help, i'll add to the project on next release.

**Comment by astrago** [comment]
Thank you for your work and look forward to the next release. Best of luck!

**Pull request merged**
